version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=4000  # Correct: Port to listen on
      - MONGODB_URI=mongodb://mongo:27017/FoodDelevery  # Correct: MongoDB connection

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules

  admin:
    build: ./admin
    container_name: admin_container
    ports:
      - "5174:5174"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./admin:/app
      - /app/node_modules

volumes:
  mongo_data:
